# Jekyll configuration for GitHub Pages

# Exclude node_modules and other unnecessary files from Jekyll processing
exclude:
  - node_modules/
  - frontend/node_modules/
  - backend/node_modules/
  - package.json
  - package-lock.json
  - frontend/package.json
  - backend/package.json
  - README.md
  - .gitignore
  - .git/
